language: scala
scala:
  - 2.12.0
  - 2.12.1
  - 2.12.2
  - 2.12.3
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
  - if [ "$TRAVIS_BRANCH" = "master" ]; then sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues ; fi
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls
