language: scala
scala:
  - 2.12.10
  - 2.13.3
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.ivy2/cache
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls
